# Generated by Django 5.0.1 on 2024-02-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0003_alter_shop_logo_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/2024/02/category.png', upload_to='category/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(default='shop_logo/2024/02/shoplogo1.jpg', upload_to='shop_logo/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/2024/02/avatardefault.jpg', upload_to='user/%Y/%m'),
        ),
    ]
