# Generated by Django 5.0.1 on 2024-02-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/2024/02/category_logo.png', upload_to='category/%Y/%m'),
        ),
    ]
