# Generated by Django 5.0.1 on 2024-02-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
